# Generated by Django 3.2 on 2025-05-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='user_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
