# Generated by Django 3.2 on 2025-04-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_uploaded_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
