# Generated by Django 3.2 on 2025-05-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_completed_surveys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completed_surveys',
        ),
    ]
